tendermint/spec

- consensus/intro.tex
> Fix a typo

- consensus/consensus.tex
Clarify condition semantic and timeouts
Improve descriptions
> Few clarifications

- consensus/conclusion.tex
- consensus/consensus.tex
Fix #36 and #37 and add few clarifications and small improvements.
> Ensure that rules are mutually exclusive

- spec/README.md
- spec/abci/README.md
- spec/abci/abci.md
- spec/abci/apps.md
- spec/abci/client-server.md
- move the abci spec from tendermint to spec repo
> Add ABCI SPEC

- spec/consensus/signing.md
- Add more details about nil votes and about amnesia attacks
> spec/consensus/signing: add more details about nil and amnesia

- spec/consensus/consensus-paper/definitions.tex
Model section was having some inconsistencies and gossip communication property was not completely specified (guarantees on send were missing).
> Fix model section

- spec/blockchain/encoding.md
Corresponding to https://github.com/tendermint/tendermint/pull/4190
> Add sr25519 amino documentation

- spec/consensus/readme.md
> Fix link in readme

- spec/p2p/peer.md
Updates the spec with the Merlin based malleability fixes. Closes #70 .
> Update the spec with Merlin based malleability fixes

- spec/abci/abci.md
- spec/blockchain/state.md
- this pr is grouped together with https://github.com/tendermint/tendermint/pull/4254, once that PR is merged then this one can be as well.
> evidence: Add time to evidence params

- .github/workflows/action.yml
- spec/README.md
- spec/consensus/fork-accountability.md
- spec/consensus/light-client.md
- spec/consensus/readme.md
- spec/p2p/node.md
- spec/reactors/consensus/consensus.md
- spec/reactors/mempool/reactor.md
As with the tendermint repo
https://github.com/gaurav-nelson/github-action-markdown-link-check
> Add markdown link checker

- .github/CODEOWNERS
- added some codeowners
please comment if youd like to be added as well.
> codeowners: add code owners

- .idea/vcs.xml
> remove .idea dir

- rfc/001-block-retention.md
> accept RFC-001

- spec/abci/abci.md
- add link to nothing at stake problem
- add cosmos-sdk example
> abci: update MaxAgeNumBlocks & MaxAgeDuration docs

- spec/abci/abci.md
- spec/abci/apps.md
- spec/abci/client-server.md
- spec/reactors/state_sync/reactor.md
The corresponding Tendermint PRs are https://github.com/tendermint/tendermint/pull/4704 and https://github.com/tendermint/tendermint/pull/4705.
We should probably add a guide that reads more like a hands-on tutorial as well, with actual commands and examples. I'll write this as part of the release package.
> document state sync ABCI interface and P2P protocol

- spec/reactors/pex/pex.md
https://github.com/tendermint/tendermint/pull/4810/files
> reactors/pex: specify hash function

- spec/abci/abci.md
- spec/blockchain/blockchain.md
Refs: https://github.com/tendermint/tendermint/issues/1007
PR: https://github.com/tendermint/tendermint/pull/4845
> spec: modify Header.LastResultsHash

- spec/abci/README.md
- spec/abci/abci.md
- spec/abci/client-server.md
- spec/blockchain/blockchain.md
to reflect the changes in tendermint repo
> spec: update evidence in blockchain.md

- spec/abci/abci.md
- spec/blockchain/blockchain.md
- spec/blockchain/state.md
https://github.com/tendermint/tendermint/pull/5031
> abci: add AppVersion to ConsensusParams

- spec/abci/apps.md
> abci: tweak node sync estimate

- spec/abci/abci.md
Refs https://github.com/tendermint/tendermint/issues/3732
> spec/abci: expand on Validator#Address

- spec/consensus/consensus.md
Refs https://github.com/tendermint/tendermint/issues/2769
> spec/consensus: canonical vs subjective commit

- spec/core/data_structures.md
- spec/core/encoding.md
Related to https://github.com/tendermint/tendermint/pull/5193.
> update hashing of empty inputs, and initial block LastResultsHash

- rfc/002-nonzero-genesis.md
Implemented in https://github.com/tendermint/tendermint/pull/5191.
> accept RFC-002

- spec/abci/abci.md
- spec/core/data_structures.md
Update following changes in https://github.com/tendermint/tendermint/pull/5237.
> update ResponseInitChain.app_hash description

- spec/abci/apps.md
Add BeginBlock & replay protection sections
> docs: add sections to abci

- spec/abci/abci.md
- spec/abci/apps.md
- spec/core/state.md
Update abci spec tags to events
> spec: update abci events

- spec/reactors/mempool/messages.md
- spec/reactors/mempool/reactor.md
Refs https://github.com/tendermint/tendermint/issues/625
> spec/reactors/mempool: batch txs per peer

- spec/abci/abci.md
- spec/abci/apps.md
- spec/abci/client-server.md
- spec/core/data_structures.md
- spec/core/encoding.md
- spec/core/state.md
- spec/p2p/connection.md
- spec/p2p/peer.md
Spec changes related to protobuf
> spec: protobuf changes

- .github/ISSUE_TEMPLATE/proposal.md
- .github/workflows/linter.yml
Add an issue template for protocol proposal changes.
> github: issue template for proposals

- spec/blockchain/readme.md
- remove blockchain section from docs site
> docs: make blockchain not viewable

- spec/core/encoding.md
- spec/core/readme.md
- add secp256k1
- reference zip 215
- migrate types to tables
closes #107
> encoding: add secp, ref zip215, tables

- spec/abci/abci.md
> abci: lastcommitinfo.round extra sentence

- rust-spec/lightclient/attacks/isolate-attackers_001_draft.md
This is the first draft of the English specification. It will be accompanied by a TLA+ model showing completeness of the approach.
> Draft of evidence handling for discussion

- rust-spec/lightclient/attacks/Blockchain_003_draft.tla
- rust-spec/lightclient/attacks/Isolation_001_draft.tla
- rust-spec/lightclient/attacks/LCVerificationApi_003_draft.tla
- rust-spec/lightclient/attacks/MC_5_3.tla
This is the intermediate spec for the larger PR.
> The TLA+ specification of the attackers detection

- spec/README.md
- spec/abci/README.md
- spec/blockchain/readme.md
- spec/consensus/readme.md
- spec/core/readme.md
- spec/light-client/README.md
- spec/p2p/readme.md
- add exact title for sections.
- don't display blockchain section
> layout: add section titles

- proto/p2p/pex.proto
- spec/p2p/messages/pex.md
Change pex message naming convention
> pex: message ergonomics

- spec/abci/abci.md
- spec/consensus/bft-time.md
- spec/core/data_structures.md
- remove blocktimeiota from params
- merge consensusparams and abci params
> params: remove block timeiota

- README.md
- rust-spec/fastsync/README.md
- rust-spec/lightclient/README.md
- rust-spec/lightclient/verification/README.md
> readme: cleanup

- spec/core/genesis.md
Add explanation for genesis
closes #161
> genesis: Explain fields in genesis file

- spec/README.md
> p2p: links

- proto/consensus/types.proto
- spec/consensus/consensus.md
- spec/p2p/messages/consensus.md
https://github.com/tendermint/tendermint/pull/6287
> msgs: rename HasVote to ReceivedVote

- CHANGELOG.md
- spec/rpc/README.md
Clarify timestamp details in RPC spec.
> rpc: clarify timestamps

- spec/rpc/README.md
reflects the changes in: https://github.com/tendermint/tendermint/pull/6445
> rpc: add chunked genesis endpoint

- proto/abci/types.proto
- spec/abci/abci.md
- spec/abci/apps.md
> ResponseCheckTx Updates

- spec/light-client/detection/detection_003_reviewed.md
- spec/light-client/verification/verification_001_published.md
- spec/light-client/verification/verification_002_draft.md
> light: address discrepancies between spec and go

- .github/workflows/stale.yml
updates the stale bot so it won't close issues
> ci: ignore issues with stale bot

- spec/consensus/evidence.md
- spec/core/data_structures.md
> evidence: add section explaining evidence

- spec/rpc/README.md
Supports changes from https://github.com/tendermint/tendermint/pull/6820
> rpc: update peer format in specification in NetInfo operation

- spec/abci/README.md
[Rendered](https://github.com/tendermint/spec/blob/wb/abci-readme/spec/abci/README.md)
Part of: #316
> abci: clarify what abci stands for

- spec/abci/abci.md
This pull requests offers several fixups to the `abci.md` document. The changes are primarily in areas that I found somewhat unclear.
> abci.md fixup

- spec/light-client/supervisor/supervisor_001_draft.md
- spec/light-client/supervisor/supervisor_002_draft.md
- spec/light-client/verification/verification_001_published.md
- spec/light-client/verification/verification_003_draft.md
> light: update initialization description

- .github/workflows/action.yml
- .github/workflows/linter.yml
Make sure it runs for pull requests as well as pushes to master.
Otherwise, I think, it may not trigger to satisfy the requirement.
A possible solution to the stuckness on #385.
> Attempt to fix the markdown link checker.

- spec/consensus/proposer-based-timestamp/tla/TendermintPBT_002_draft.tla
- spec/consensus/proposer-based-timestamp/tla/typedefs.tla
First version of draft 002, with Apalache type annotations. See #395.
> PBT draft 002: Apalache annotations

- proto/tendermint/abci/types.proto
- spec/abci++/abci++_methods_002_draft.md
As discussed with @cmwaters  and @williambanfield
> Merge PR#392 (verbatim) into master
